### ISSUE TITLE
API to detect if animations are enabled?

### ISSUE THREAD

**Issue by bootstraponline** [linkedin/test-butler#1]
`AnimationDisabler` has `disableAnimations` and `enableAnimations` however there's no method to detect the status of animations. This is useful to assert that animations are actually disabled.

What do you think about adding `getAnimationScaleFactors`?

**Comment by drewhannay** [comment]
Hm, so right now we don't expose a way for test authors to enable/disable animations. It's just part of the general setup/teardown. I could imagine it being useful to verify that all of the setup steps succeeded and fail setup if they didn't. Would that cover the use case you're thinking of?

**Comment by bootstraponline** [comment]
> I could imagine it being useful to verify that all of the setup steps succeeded and fail setup if they didn't. Would that cover the use case you're thinking of?

Yes

**Comment by SKART1** [comment]
May be it is better to remove disabling animation and other stuff from `setup` `teardown` methods? Because using this library as standard apk on real devices for for-example disabling internaet or rotating screen is not possible because of  this additional steps

**Comment by bootstraponline** [comment]
The default is to fail gracefully even if steps such as disabling animations don't work. That shouldn't cause problems on real devices.

The issue with the current design is that there's no way to opt-in to a fail fast mode. If configuration fails then I'd prefer the test suite error.

**Comment by drewhannay** [comment]
I experimented with several ways to implement this, and settled on the original proposal, exposing a method to assert that animations are currently disabled.

What I struggled with is which steps of `setup` are worth failing over? Each user may have a different opinion on what that set should be, and exposing a way to configure all of them would greatly increase the complexity of Test Butler's public api, which I'd like to avoid. So for now we can just expose the animation status check and if a good solution presents itself in the future, we can revisit.

**Comment by bootstraponline** [comment]
Sounds good.

**Comment by shashikumarraja** [comment]
How to do you integrate this ExampleTestRunner in your code.
I tried creating a class with the same name and then modified build.gradle to have
testInstrumentationRunner 'my_package_path.ExampleTestRunner by replacing
testInstrumentationRunner 'android.support.test.runner.AndroidJUnitRunner'.But its not working.
Can you please explain the detailed steps of implementing Test Butler

**Comment by Kisty** [comment]
@shashikumarraja What does your ExampleTestRunner look like? And what package is the class actually in?
