### ISSUE TITLE
What does this mean "can only be installed on emulators that use the stock Android keystore"

### ISSUE THREAD

**Issue by prolificcoder** [linkedin/test-butler#10]
From the readme.md 

Does it mean that I can't use it to run on default android emulators that are created with avd? How about genymotion

**Comment by drewhannay** [comment]
The default android emulators and Genymotion both use the stock Android keystore from AOSP. The documentation is just being cautious because there might be additional devices or emulators that use that stock keystore that we don't know about 😄
