### ISSUE TITLE
Could not find com.linkedin.testbutler:test-butler-api:2.1.0

### ISSUE THREAD

**Issue by ligi** [linkedin/test-butler#103]
when updating from test-butler 2.0.0 to 2.1.0 I get the following error:
```

> Could not resolve all artifacts for configuration ':trulesk:releaseCompileClasspath'.
   > Could not find com.linkedin.testbutler:test-butler-api:2.1.0.
     Required by:
         project :trulesk > com.linkedin.testbutler:test-butler-library:2.1.0
```

I am having jcenter in my repositories

**Comment by drewhannay** [comment]
Ah, my apologies! This is a new artifact and I forgot to go tell Bintray to sync it to jcenter. I just made that request, but I think it can maybe take a day or two for them to approve. I'll try to check back and let you know when it's available, but it should just start working at some point soon.

**Comment by ligi** [comment]
thanks for the fast answer and your work in general - much appreciated!

**Comment by drewhannay** [comment]
Okay, it should be available now! Feel free to reopen this if it still doesn't work.

**Comment by ligi** [comment]
Thanks it is available now!

one fast question - perhaps you have an idea about this:
