### ISSUE TITLE
Set cursor drawable to empty in tests

### ISSUE THREAD

**Issue by chao2zhang** [linkedin/test-butler#107]
Cursor is part of animating parts on a TextView when executing tests. I am wondering if this is TestButlet's scope to disable the cursor (or set it to white by default) so that we can get reliable screenshots.

In addition, the EdgeEffect of a RecyclerView and the scroll bar of a View can be discussed altogether in this thread.

**Comment by drewhannay** [comment]
It might be okay to add this if we can do it in a way that's disabled by default, since I'm guessing many use cases still want to see the cursor and EdgeEffect. Do you have an idea of what the implementation would look like?

**Comment by chao2zhang** [comment]
The solution turns out to be overriding the theme attributes in test code. And the purpose of this is visual regression tests, not necessarily the usual assertion tests code that test-butler.

I am now leaning towards not building this solution in test-butler, please let me know otherwise.

**Comment by drewhannay** [comment]
Sounds good to me, thanks for investigating.
