### ISSUE TITLE
Where do I get the TestButler APK from?

### ISSUE THREAD

**Issue by MiralDesai** [linkedin/test-butler#11]
Is it not in the repo? Just had a quick look and cannot find anything.

Do we have to build it ourselves? Not sure why we would have to do that. Might be a good addition to the repo if I'm not just being a bit blind.

**Comment by bootstraponline** [comment]
I think the readme should be updated to point to the maven download URL. In general keeping binaries in a git repo isn't great.

**Comment by bootstraponline** [comment]
Here's the link:
> https://bintray.com/drewhannay/maven/download_file?file_path=com%2Flinkedin%2Ftestbutler%2Ftest-butler-app%2F1.0.0%2Ftest-butler-app-1.0.0.apk

> https://bintray.com/drewhannay/maven/test-butler-library
> https://bintray.com/drewhannay/maven/test-butler-app/

**Comment by kirillzh** [comment]
App link doesn't have package: `No direct downloads selected for this package.`

**Comment by bootstraponline** [comment]
The repo moved:
https://bintray.com/linkedin/maven/test-butler-app/

**Comment by kirillzh** [comment]
Ah, found it, sources and packages are in `Files` tab.

**Comment by arnaudambro** [comment]
for new comers, the links above are broken
https://search.maven.org/artifact/com.linkedin.testbutler/test-butler-app/2.2.1/apk
