### ISSUE TITLE
Can't resolve androidTestUtil

### ISSUE THREAD

**Issue by bohsen** [linkedin/test-butler#111]
Maybe I just have to wait a bit, but just wanted to raise awareness.
After the library was moved to MavenCentral I'm getting the following error:

```gradle
Gradle sync failed: Could not resolve all files for configuration ':app:androidTestUtil'.
Could not find com.linkedin.testbutler:test-butler-app:2.2.1.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.pom
- https://jcenter.bintray.com/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.pom
- https://dl.google.com/dl/android/maven2/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.pom
- https://jitpack.io/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.pom
```

It doesn't show on [mavens repository search](https://search.maven.org/search?q=com.linkedin.testbutler).

And also thx for a great library.

**Comment by drewhannay** [comment]
Wow, you're very prompt 😄 

Since this is our first release to Maven Central, we're waiting on them to set up and approve the sync, after which releases should be all in our control. Hopefully that will happen tomorrow, but I'll update here once it's confirmed. Thanks!

**Comment by drewhannay** [comment]
It should be available now! I just tested in a sample project. It may take a bit longer to show up on search.maven.org, but the artifacts are available.
