### ISSUE TITLE
Follow-up on #109 to remove Bintray references from readme.md

### ISSUE THREAD

**Issue by TWiStErRob** [linkedin/test-butler#113]
After merging https://github.com/linkedin/test-butler/pull/109, as far as I can see jcenter() has the older versions and mavenCentral() only has the new version:
https://mvnrepository.com/artifact/com.linkedin.testbutler/test-butler-library

I think the repo readme needs adjusting since it references Bintray.

**Comment by cckroets** [comment]
Thanks for raising this. Working on a fix.

**Comment by cckroets** [comment]
Fixed by https://github.com/linkedin/test-butler/pull/114
