### ISSUE TITLE
https://b.corp.google.com/issues/37057596 is fixed

### ISSUE THREAD

**Issue by skywalkerdude** [linkedin/test-butler#115]
```
Also, you can use methods in the TestButler class in the @BeforeClass & @AfterClass of a test class. However, be warned that the test suite will not report that the Test Butler app is not installed, instead it will skip the test. This is due to a bug in Android testing support.
```

Just a heads up, but https://b.corp.google.com/issues/37057596 has been fixed for some time now and we are way past runner version v1.0.2 (https://b.corp.google.com/issues/37057596#comment11). Might be good to update the README :)

**Comment by kkoser** [comment]
Thanks, fixed with #116
