### ISSUE TITLE
AnimationsUtil.loadAnimation is not going to be disabled by TestButler

### ISSUE THREAD

**Issue by chao2zhang** [linkedin/test-butler#118]
## Issue
When using `AnimationsUtil.loadAnimation` to apply animation to views, TestButler does not seem to disable the animation correctly, resulting in main looper keep receiving the choreographer frame refresh.

## How to reproduce?
https://github.com/chao2zhang/test-butler/commit/30786d33a29f89d2e269783c66da98df63f3ed2a
Run `AnimationDisablerTest.disableAnimations()`. The test now hangs forever.

**Comment by cckroets** [comment]
`AnimationsUtil.loadAnimation(id)` does not automatically apply the `ANIMATOR_DURATION_SCALE` OS setting that TestButler sets, so developers need to apply this scale manually.
