### ISSUE TITLE
Test butler as standard application

### ISSUE THREAD

**Issue by SKART1** [linkedin/test-butler#16]
In our company we are building android testing farm which consist not only from virtual devices but also has some real devices. Installing system signed application on a such device is really painfully. 
So  it will be great to have to assembles of this application:

1. Full-functionality signed with system key
2. Reduced functionality - unsigned, but still able to rotate screen, disable wi-fi and etc. As this actions may be done by linear application

**Comment by drewhannay** [comment]
This is probably not something that will be supported from this project. The goal of Test Butler is to make it as easy and as close to 100% reliable as possible for developers to write stable tests. Real devices are inherently going to be an order of magnitude less stable than emulators, and we don't believe there's much value in running UI tests on real devices (outside of performance testing and monkey testing). Much of Test Butler's current or planned functionality also requires a rooted device, so there really wouldn't be many features that would work on real devices anyway. Plus device OEMs could potential customize their version of Android to where Test Butler would need a lot of OEM-specific code, which we want to avoid.

For a more detailed argument, check out this presentation from Google's Espresso team:
https://www.youtube.com/watch?v=aHcmsK9jfGU

**Comment by SKART1** [comment]
I have watched this video completly. 
At the same time Facebook and Google have HUGE farm of real devices.  [Here](https://code.facebook.com/posts/300815046928882?attachment_canonical_url=https%3A%2F%2Fcode.facebook.com%2Fposts%2F300815046928882) is the article from FB what about google can not find an article

Rotate screen and disable wifi actually do not require root but special permissions only
