### ISSUE TITLE
Disable spell-checker

### ISSUE THREAD

**Issue by ligi** [linkedin/test-butler#2]
Another source for flakyness in tests is the spell-checker as this can pop-up suggestions and then tests fail. So my suggestion for an enhancement would be to disable spell-checking like animations

**Comment by bootstraponline** [comment]
Is there code somewhere that shows how to do this? On Espresso, I use `replaceText` to bypass spell check.

**Comment by ligi** [comment]
I am doing this manually currently - just thought it would be a nice enhancement. I do not read that replaceText bypasses spell-checking in the documentation: https://developer.android.com/reference/android/support/test/espresso/action/ViewActions.html#replaceText(java.lang.String)
will try it out - thanks for the fast feedback

**Comment by bootstraponline** [comment]
It looks like you can do:


```java
editText.setInputType(InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);
```

> http://stackoverflow.com/questions/6281514/android-programmatically-disable-autocomplete-autosuggest-for-edittext-in-emulat

**Comment by drewhannay** [comment]
If you can provide more details on what you're currently doing to handle this, that might be useful too.

**Comment by ligi** [comment]
@bootstraponline: but In the app I want this - or do you mean create a custom ViewAction
@drewhannay currently I am going into the settings and disable the spell-checker - but everytime I add a new emulator this strikes me again - so having it in a place like this lib would be great - hence this suggestion

**Comment by bootstraponline** [comment]
There might be a way to disable spell check globally via the keyboard settings on the emulator. It's not clear how you'd do this via code though.

> http://www.greenbot.com/article/2158764/how-to-disable-autocorrect-on-android.html

**Comment by drewhannay** [comment]
If it's something that you change in the system settings app, it's very likely that there's an item in the settings database for it. And that means we should be able to modify it from Test Butler, the same way we modify location settings.

**Comment by Kisty** [comment]
Looks like there is a [`SPELL_CHECKER_ENABLED`](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/provider/Settings.java#5878) field in android.provider.Settings if that helps.

I guess you could change it using this method: http://stackoverflow.com/a/11985349/818821

**Comment by drewhannay** [comment]
@ligi Can you tell me which emulator configuration / api level you're seeing this issue on? We've never seen it in any of our tests at LinkedIn and I haven't heard this complaint before, so it'd be nice to have a little more info before adding support to Test Butler (it should be pretty easy to add though).

**Comment by drewhannay** [comment]
We were just able to reproduce this internally (hard to believe we were so lucky to never hit it until now). Right now I'm thinking we'll disable the spell checker by default, and provide a method in the library for toggling it on and off so apps can still turn it on if they want to.

**Comment by ligi** [comment]
That's great news! Yea it is really rare ( yet annoying when it happens ) - that was also the reason why I could not provide you with an example of it happening - was not able to reproduce it - just sometimes seeing it
