### ISSUE TITLE
Crash not dismissed

### ISSUE THREAD

**Issue by marcorighini** [linkedin/test-butler#20]
During emulator startup I experience the crash "launcher3 has stopped". When running tests I see that the dialog is not dismissed automatically and my tests are failing with: 
`java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong.`

I've followed the readme: installed the app on emulator, created and enabled custom testrunner, added library to androidTestCompile task.

Thanks for the help,
Marco

**Comment by drewhannay** [comment]
hmm, if the crash happened before Test Butler was installed, I'm not sure there's a way for us to dismiss the dialog. One option might be to use adb to send a back button key event to the emulator after it finishes starting (assuming that will dismiss any crash dialogs that might have appeared). I don't think Test Butler can help with this case though unfortunately

**Comment by marcorighini** [comment]
TestButler is installed previous than running the app
