### ISSUE TITLE
Upload 1.0.1 with setGsmState method

### ISSUE THREAD

**Issue by Kisty** [linkedin/test-butler#23]
Would be great to use the setGsmState method but can't using Bintray and cloning and integrating the source into my project is a bit hard.

**Comment by drewhannay** [comment]
We're actively working on this. We're trying to move the Test Butler bintray repo from my personal account to the new LinkedIn account and keep having to go back and forth with bintray's support team. Hopefully this will be resolved soon and then we'll publish the new version.

**Comment by bootstraponline** [comment]
looks like this is done:
https://github.com/linkedin/test-butler/pull/26

**Comment by drewhannay** [comment]
Yep!

**Comment by Kisty** [comment]
Thanks for notifying 👍
