### ISSUE TITLE
Preserve original value of animation settings after teardown

### ISSUE THREAD

**Issue by bootstraponline** [linkedin/test-butler#25]
Animations are unconditionally enabled on `TestButler.teardown`. It'd be nice to pass some options to teardown to either keep animations disabled or at least preserve their original value.

**Comment by drewhannay** [comment]
Preserving the original value makes sense...I think I had noticed that before and forgot to make an issue. I'll edit the issue title.

**Comment by Kisty** [comment]
Not sure if this should be its own issue but does the disabling animations take care of the Window, Transition and Animator scales altogether?

**Comment by drewhannay** [comment]
Yes, it changes all three settings. Are you wanting to change individual settings? I think that would probably be out of scope for Test Butler, since Test Butler is really just for automated tests, not necessarily a utility for general development.

**Comment by Kisty** [comment]
Ah great.  That's all I needed to know. No, I don't want to be able to control them individually but I find working with the emulator with no animations makes it quicker to develop with.
