### ISSUE TITLE
Where is the artifact located?

### ISSUE THREAD

**Issue by jurenovic** [linkedin/test-butler#3]
Hi,

added the described `androidTestCompile 'com.linkedin.android.testbutler:test-butler-library:1.0.0'` but I get `      > Could not find com.linkedin.android.testbutler:test-butler-library:1.0.0.`

Tried search maven.org and bintray.com but nothing is there.

**Comment by joluet** [comment]
It's actually `com.linkedin.testbutler:test-butler-library:1.0.0` instead of `com.linkedin.android.testbutler:test-butler-library:1.0.0`. See https://bintray.com/drewhannay/maven/test-butler-library

**Comment by jurenovic** [comment]
@joluet Tnx for a fast comment. I think README should be updated. Feel free to close this issue.

**Comment by drewhannay** [comment]
Thanks @jurenovic and @joluet. Just fixed the README.

**Comment by shareme** [comment]
no its not fixed still cannot get the artifact just tried both urls

**Comment by meghalshah** [comment]
It seems like it has been removed, bintray link is 404ing

https://bintray.com/drewhannay/maven/test-butler-app/

**Comment by bootstraponline** [comment]
New link is: https://bintray.com/linkedin/maven/test-butler-app/

**Comment by drewhannay** [comment]
Sorry everyone, we were moving the bintray repo from my personal account to LinkedIn and it looks like Bintray deleted my personal one without telling me (we thought we could delete it manually later and update the README at that time).

Thanks for the pull request @bootstraponline !
