### ISSUE TITLE
'No tests were found' error

### ISSUE THREAD

**Issue by heitorcolangelo** [linkedin/test-butler#4]
Hi, I'm facing some difficult trying to start using test-butler.
First, I've created another class that extends AndroidJUnitRunner:
```java
public class CustomTestRunner extends AndroidJUnitRunner {
  @Override
  public void onStart() {
    TestButler.setup(InstrumentationRegistry.getTargetContext());
    super.onStart();
  }

  @Override
  public void finish(int resultCode, Bundle results) {
    TestButler.teardown(InstrumentationRegistry.getTargetContext());
    super.finish(resultCode, results);
  }
}
```

Then I changed this line on my build.gradle app:
```java
defaultConfig{
    testInstrumentationRunner "com.example.heitorcolangelo.espressotests.CustomTestRunner"
}
```
But when I run my tests, I got 'No tests were found' error.

Second, how can I install the Test Butler apk? Should I clone the project and build it?
Can you help me with theses two points please?
Thanks!

**Comment by drewhannay** [comment]
Hey Heitor,

Can you check the "Edit Configurations" dialog in Android Studio and see if it lists your custom test runner there under "Specific instrumentation runner"? Android Studio is supposed to pick up that setting from Gradle, but if it's not set for some reason, that could lead to the "No tests found" issue.

For installing the Test Butler apk, you can download it manually from [bintray](https://bintray.com/drewhannay/maven/test-butler-app#files/com/linkedin/testbutler/test-butler-app) and install it.

The more complicated (but better) solution is to include it as a gradle dependency and add a gradle task that installs the file on the emulator. A good feature addition for Test Butler would be to include a gradle plugin piece that adds this dependency & task. At LinkedIn we currently have some custom scripts that do this, but it's not part of the Test Butler project yet.

**Comment by drewhannay** [comment]
Also, for the first issue, can you check logcat and see if there's a crash stack trace there? I think sometimes when Android Studio shows "No tests found", it can mean something crashed before tests started running.

**Comment by stoyicker** [comment]
I think you also may need to register the instrumentation in your (test) manifest file.

**Comment by heitorcolangelo** [comment]
@drewhannay and @stoyicker 
Thanks for your reply.
I was busy during all day and wasn't able to try again with your responses.
I'll try it tonight and then I return here.
Thanks anyway.

**Comment by heitorcolangelo** [comment]
@drewhannay 
I had to change manually "Specific instrumentation runner" in "Edit Configurations", than worked.
Also, I was able to download the apk and install it in the emulator.
Thank you!
I hope that this script for test butler apk installation can be incorporated in the project in the future.

**Comment by drewhannay** [comment]
Great, glad you got things working.
