### ISSUE TITLE
Can't install on emulator with Google API

### ISSUE THREAD

**Issue by smdremedy** [linkedin/test-butler#44]
APK can be installed on the emulator with android-24 image, but the same emulator with Google API causes:
`
Failed to install test-butler-app-1.1.0.apk: Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package couldn't be installed in /data/app/com.linkedin.android.testbutler-1: Package com.linkedin.android.testbutler has no signatures that match those in shared user android.uid.system; ignoring!]
` 
Can this be fixed in any way? Platform 25 does not have images without Google API at this point.

**Comment by drewhannay** [comment]
If the system keystore for the Google APIs emulators is public like the non-Google APIs emulators, then we could make a variant of Test Butler that works for those emulators. But if not, I don't think there's anything we can do. It's a bit concerning that API 25 doesn't have an image without Google APIs, not just for test butler, but for developer testing in general. 😞 

I did a (VERY) quick search and didn't see the keystore for Google APIs emulators available, but feel free to reopen this if I missed it somewhere.

**Comment by Kisty** [comment]
I'm pretty sure I've been running API 25 with Google APIs on an emulator with TB 1.0.1 running fine...

**Comment by tomkoptel** [comment]
I am still reproducing this behavior. Is there any way we can extract key store that Google API shipped emulators use?

**Comment by nicks258** [comment]
Remove `android:sharedUserId` from the **menifest** file of test-butler-app.

**Comment by weitzj** [comment]
I happen to run into this problem as well, but only for:

- Android O Beta on an actual device
- the new Android O (API26) emulators (Google Play, Google APIs)
- the new Android Nougat (API25) emulators with Google Play

Works find on Android Nougat (API25) emulator with Google APIs

**Comment by ligi** [comment]
I am now also facing this problem. Was running an emulator 25 with google-apis before with test-butler - but when recreating this emulator I am also getting:

`Failed to install test-butler-app-1.3.1.apk: Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package couldn't be installed in /data/app/com.linkedin.android.testbutler-Fyya9bfxBI9dEauibDCf8g==: Package com.linkedin.android.testbutler has no signatures that match those in shared user android.uid.system; ignoring!]
`

seems google made changes to the emulator so this is not possible anymore ..-(

**Comment by AlbertVilaCalvo** [comment]
To get rid of the error I've had to use an emulator without Google APIs (API 21).

**Comment by Kisty** [comment]
Have asked Google to produce AOSP images for missing ones and they're taking it on! 😄https://issuetracker.google.com/issues/79784000

**Comment by KirioXX** [comment]
I'm still seeing this issue on v2.0.1 on a Pixel 3a XL emulator with API 28 without Google APIs.
Is there anything else to get arround this issue?

**Comment by arjun1194** [comment]
> android:sharedUserId

How do i remove this property can someone please give steps ? 
Where to go?
Which project to open ?
which manifest are you refering to , i cant see it in my manifest.xml

**Comment by arjun1194** [comment]
No response ??? How do i run this please someone help
