### ISSUE TITLE
java.lang.IllegalStateException: ButlerService is not started!

### ISSUE THREAD

**Issue by HernanRossi** [linkedin/test-butler#46]
Hello, I have setup TestButler as specified except that the test that I am running was created with Espresso Recorder and I extended the class it created with AndroidJUnitRunner. I installed the TestButler .apk through the terminal with adb install. However when I attempt to use a test butler method within the espresso test I get the error mentioned above. Any help would be greatly appreciated. Thank you.

**Comment by Kisty** [comment]
Are you running the tests on an emulator? And does the apk version match the version of the library?

**Comment by HernanRossi** [comment]
Yes for both questions. Thank you for the reply.

**Comment by Kisty** [comment]
No worries. Try unplugging all Android devices, close all emulators so there's only one emulator,  uninstall the test butler apk, do clean build, then drag apk file onto emulator and run the tests again.

**Comment by kenyee** [comment]
FWIW, I'm having the same issue...fresh install 1.2.0 for plugin and APK.  The test butler APK doesn't show up as an app icon to run so it can't be found via the launcher...would be nice if there were a simple UI to show that it's installed and what the status of it is.

**Comment by Kisty** [comment]
I like the idea of a simple UI to show its status. Would help for validating if app is installed and if OK.

**Comment by kenyee** [comment]
Tried it on an AVD emulator w/ Google APIs and API 25 and have the same error msg.  It's like it can't talk to the installed APK which I presume has the magic service that lets it turn off/on the settings switches for wifi, rotation, etc.

**Comment by kenyee** [comment]
Also tried version 1.1.0 with the same error.  My test right now is fairly trivial and the latest support libs are being used (25.1.0) for the latest support annotations:


```
package test.com.offlineokhttptest;

import android.os.Bundle;
import android.support.test.InstrumentationRegistry;
import android.support.test.runner.AndroidJUnit4;
import android.support.test.runner.AndroidJUnitRunner;

import com.linkedin.android.testbutler.TestButler;

import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.IOException;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

import static org.junit.Assert.assertEquals;

/**
 * Tests ability for okhttp to survive offlining
 */
@RunWith(AndroidJUnit4.class)
public class OkHttpCrapNetworkTest extends AndroidJUnitRunner {
    @Override
    public void onStart() {
        TestButler.setup(InstrumentationRegistry.getTargetContext());
        super.onStart();
    }

    @Override
    public void finish(int resultCode, Bundle results) {
        TestButler.teardown(InstrumentationRegistry.getTargetContext());
        super.finish(resultCode, results);
    }


    @Test
    public void verifyOkHttpCanReadSite() throws IOException {
        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder()
                .url("https://www.google.com")
                .build();

        Response response = client.newCall(request).execute();
        assertEquals(response.code(), 200);
    }

    @Test
    public void verifyOkHttpCannotReadSiteWithNetworkDown() throws IOException {
        TestButler.setGsmState(false);
        TestButler.setWifiState(false);

        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder()
                .url("https://www.google.com")
                .build();


        Response response = client.newCall(request).execute();
        assertEquals(response.code(), 200);
    }
}
```

**Comment by kenyee** [comment]
The last test will obviously fail but before it gets to the assert, it fails in TestButler.setGsmState with:

```
java.lang.IllegalStateException: ButlerService is not started!
at com.linkedin.android.testbutler.TestButler.verifyApiReady(TestButler.java:278)
at com.linkedin.android.testbutler.TestButler.setGsmState(TestButler.java:181)
```

**Comment by kenyee** [comment]
![screen shot 2017-01-31 at 10 47 00 am](https://cloud.githubusercontent.com/assets/586670/22472115/9c1f398e-e7a2-11e6-8cc2-e3cfc83e46d2.png)

What's weird is the Test Butler helper app isn't running, though if it's just a service, it'll shut down as soon as nothing is connected to it or it's not handling anything...

**Comment by drewhannay** [comment]
Have you set the `testInstrumentationRunner` property in your `build.gradle` file? It looks like this step is not included in the README, but you can see an example in the [demo project](https://github.com/linkedin/test-butler/blob/master/test-butler-demo/build.gradle). You can verify by adding some log statements to your `onStart` method to check if it's being called.

Also btw, you shouldn't need `@RunWith` if you're using a custom test harness that extends `AndroidJUnitRunner`

**Comment by drewhannay** [comment]
Haven't heard anything back on this one, so I'm going to assume you figured it out. Feel free to re-open with more info if that's not the case.
