### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by andreij7** [linkedin/test-butler#5]
I need to support minSdkVersion 14. Would changing that minSdkVersion from 15 to 14 be doable?

**Comment by drewhannay** [comment]
I'm not aware of anything that would prevent this. All of LinkedIn's apps are minSdkVersion 15, which is the only reason for this 😄 

If you want to try it out and send a pull request, go for it. Otherwise I will try to make time to test it out soon.

**Comment by andreij7** [comment]
ok thanks

**Comment by andreij7** [comment]
I may have to come back to test-butler.  We are just starting to use the AWS Device farm and i don't think i can get the butler app installed on each of those devices without integrating the source into my project and tweaking the code.
