### ISSUE TITLE
Clean up activities

### ISSUE THREAD

**Issue by bootstraponline** [linkedin/test-butler#50]
One issue I've run into using test-butler with Espresso testing, is that activities don't get cleaned up. I've had to adopt code [like this](https://github.com/nenick/espresso-macchiato/blob/bb36f444eb116e84122d59af983318c24b1688a7/espresso-macchiato/src/main/java/de/nenick/espressomacchiato/testbase/EspCloseAllActivitiesFunction.java#L43) to make sure `activity.finish();` gets called after tests run.

- Is cleaning up activities beyond the scope of test butler?
- How does linkedin deal with retrying failed tests if there's no way to close the activities from a failed run?

**Comment by drewhannay** [comment]
Yeah, I'm not sure closing activities is something that makes sense to live in Test Butler. I agree that it's a big pain point though.

At LinkedIn, we do something pretty similar to the code you posted for closing activities. We also get around this problem by using a custom test harness which only runs a single test per `instrument` command. Between each test execution, we force-stop the app and clear all package data, to ensure that the next test is starting from a completely clean state, even if the previous test failed or left activities running.

**Comment by bootstraponline** [comment]
Cool. Thanks for the info.

If it's possible, it'd be neat to see the closing activity code / custom test harness even if it doesn't live in the test-butler repo.

**Comment by drewhannay** [comment]
@bootstraponline Here's [a gist](https://gist.github.com/drewhannay/7fa758847cad8a6dc26f0d1d3cb068ad) of what we use for closing activities

The custom test harness is harder to show off, since it's a lot of code. It's fairly similar to Shazam's [Fork](https://github.com/shazam/fork) runner. I'd love to open source it someday, but right now it has too many dependencies on internal things and we haven't had the time / resources to refactor and extract the right parts.

**Comment by bootstraponline** [comment]
Thank you!! This is awesome.

**Comment by bootstraponline** [comment]
@drewhannay can you throw a license banner on those gist files? I'd like to use them at work. 😄

**Comment by drewhannay** [comment]
Done 😄

**Comment by bootstraponline** [comment]
Thanks! It's working really well with our internal tests. The changes will be in the [next open source sync](https://github.com/instructure/android-uno).
