### ISSUE TITLE
Unable to run test-butler-app

### ISSUE THREAD

**Issue by IgorGanapolsky** [linkedin/test-butler#54]
Hello,
I wish to deploy the test-butler-app onto my device.  However, in Android Studio, the build shows it cannot run due to **Default Activity not found**.
![screen shot 2017-03-09 at 3 56 07 pm](https://cloud.githubusercontent.com/assets/201209/23770421/f5b86ec4-04e0-11e7-8100-0ac621878e61.png)

How can I get around this?

**Comment by Kisty** [comment]
Try doing from command line `./gradlew :test-butler-app:installDeb`.

The app doesn't have a an activity, it's only used for when running automated tests.
