### ISSUE TITLE
java.lang.NoSuchMethodException: setActivityController

### ISSUE THREAD

**Issue by thanhlv93** [linkedin/test-butler#66]
Hi All,
I have issue when run code . My error :
Failed to install custom IActivityController: setActivityController [interface android.app.IActivityController]
java.lang.NoSuchMethodException: setActivityController [interface android.app.IActivityController]
at java.lang.Class.getMethod(Class.java:1981)
at java.lang.Class.getDeclaredMethod(Class.java:1960)

error at method :
private static void setActivityController(@Nullable IActivityController activityController) {
        try {
            Class<?> amClass = Class.forName("android.app.ActivityManagerNative");
            Method getDefault = amClass.getMethod("getDefault");
            Object am = getDefault.invoke(null);
            Log.d(TAG, "setActivityController: " + am.getClass());
            Method setMethod = am.getClass().getDeclaredMethod("setActivityController", new Class[]{IActivityController.class});
            setMethod.invoke(am, activityController);
        } catch (Throwable e) {
            Log.e(TAG, "Failed to install custom IActivityController: " + e.getMessage(), e);
        }
    }

Can you tell me how to fix this error ?

**Comment by drewhannay** [comment]
Can you share more info about your setup? What kind of emulator are you using? And what version of Test Butler?

**Comment by Kisty** [comment]
I've seen this before. You aren't using Gradle 3.5 are you? If so, try Gradle 3.4.1.

**Comment by drewhannay** [comment]
I'd be curious to know how Gradle version could cause this. We've used Test Butler with Gradle 3.5 as well as Gradle 4.0 without any issues.

**Comment by Kisty** [comment]
Ignore that last suggestion, sorry. 

Sounds like a mismatch of test butler versions on the emulator and the library version used in `androidTest`. 

1) Download and install the latest test butler APK from [here](https://bintray.com/linkedin/maven/test-butler-app/1.3.1#files/com/linkedin/testbutler/test-butler-app/1.3.1) (currently 1.3.1) on the emulator.
2) Check the test butler library is the same version as used in the code. 
e.g. 
`androidTestCompile 'com.linkedin.testbutler:test-butler-library:1.3.1'`

**Comment by thanhlv93** [comment]
Line code : Object am = getDefault.invoke(null) returned ActivityManagerProxy for me and method setActivityController not in ActivityManagerProxy . 
I using nexus 5x.

**Comment by Kisty** [comment]
I've been able to use it fine on a Nexus 5X API 25 emulator fine. Not sure what's different. What api level was the Nexus 5X and Nexus 6P at? Were they different?

**Comment by thanhlv93** [comment]
I don't know but when I run on nexus 5x with API then I have to fix code with two params. I run on simulator 6P API 23 then I don't have to fix code.

**Comment by Kisty** [comment]
Quick question: Do the emulators come with Google APIs (e.g. Google maps, etc)?

**Comment by thanhlv93** [comment]
yeah, it has Google APIs

**Comment by Kisty** [comment]
OK, try using an emulator image API 25 without Google APIs.

**Comment by thanhlv93** [comment]
I tried run with API 25 without Google APIs and it's ok. Don't need to fix code .

**Comment by Kisty** [comment]
Cool. But I am running tests on API 25 with Google APIs on my machine. It's bizarre why it's not working on your machine. 

Does it manage to do some tests and then fails on one test or does the build fail setting up tests?

**Comment by saildeep** [comment]
Is there a workaround without compiling test butler myself? Are there any other google api emulators i could use?

**Comment by Gavinpub** [comment]
Can your demo invoke setActivityController successfully ? As I know system will check if the caller has permission <android.permission.SET_ACTIVITY_WATCHER>. If no, it will fail to invoke. Unfortunately the permission is HIDE and system app use only. Is it possilbe to invoke it on 3rd party app?

**Comment by ewolfe123** [comment]
I see the same issue. Pixel Emulator, API 25 w/ Google APIs. I've verified that the apk and library versions match. I don't see a system image in sdkmanager for API 25 without Google APIs.

This issue occurs both on setup and teardown. Stack trace:
```
03-15 18:26:31.624 10149-10149/? D/ButlerService: ButlerService starting up...
03-15 18:26:31.639 10149-10149/? E/NoDialogActivityController: Failed to install custom IActivityController: setActivityController [interface android.app.IActivityController]
                                                               java.lang.NoSuchMethodException: setActivityController [interface android.app.IActivityController]
                                                                   at java.lang.Class.getMethod(Class.java:1981)
                                                                   at java.lang.Class.getMethod(Class.java:1637)
                                                                   at com.linkedin.android.testbutler.NoDialogActivityController.setActivityController(NoDialogActivityController.java:114)
                                                                   at com.linkedin.android.testbutler.NoDialogActivityController.install(NoDialogActivityController.java:95)
                                                                   at com.linkedin.android.testbutler.ButlerService.onCreate(ButlerService.java:147)
```
I am also unable to install the test butler APK on API 24 or 26.

**Comment by drewhannay** [comment]
The fix for this has been merged, I'll do a new release sometime this week.
