### ISSUE TITLE
add support to enable/disable WIFI

### ISSUE THREAD

**Issue by BogdanLivadariu** [linkedin/test-butler#67]
it would be nice to have support to manipulate the WIFI connection

**Comment by Kisty** [comment]
It's already implemented. Use [TestButler.setWifiState(boolean)](https://github.com/linkedin/test-butler/blob/master/test-butler-library/src/main/java/com/linkedin/android/testbutler/TestButler.java#L163).

**Comment by jaredsburrows** [comment]
@BogdanLivadariu This is already implemented. Can you close this issue?
