### ISSUE TITLE
Cannot install the APK(1.3.1) on an S6 device

### ISSUE THREAD

**Issue by BogdanLivadariu** [linkedin/test-butler#68]
I downloaded the apk from [here(version 1.3.1)](https://bintray.com/linkedin/maven/test-butler-app/#files/com%2Flinkedin%2Ftestbutler%2Ftest-butler-app%2F1.3.1)

tried installing it with `adb install ...`
result is this:
```
pkg: /data/local/tmp/test-butler-app-1.3.1.apk
Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE]
```

**Comment by drewhannay** [comment]
As mentioned in the [README](https://github.com/linkedin/test-butler#how-does-it-work), Test Butler only works on emulators, not physical devices. So this error is expected

**Comment by lawonga** [comment]
Is there a way for us to ignore the error without the entire test build failing?

**Comment by kkoser** [comment]
@lawonga This is a fundamental part of how Test Butler works, and there is no way around this error. If you want to run tests on real devices, you'll need to setup your code to be able to use or not use test butler based on some flag. Is that what you mean by ignore the error?
