### ISSUE TITLE
Android 8 (SDK 26) fail to install test butler app

### ISSUE THREAD

**Issue by C2H6O** [linkedin/test-butler#71]
<img width="574" alt="screen shot 2017-09-29 at 4 22 51 pm" src="https://user-images.githubusercontent.com/3132218/31039430-78415508-a532-11e7-8185-9164c2c38249.png">

**Comment by drewhannay** [comment]
Are you using the version of the emulator that includes the Google Play store? These are signed with a different key, and are not compatible with Test Butler (or some other debugging tools, like root access).

**Comment by C2H6O** [comment]
Ahh, yeah. That must be it. Thanks!

**Comment by Kisty** [comment]
Sooo, looks like Google have released AOSP images of Oreo, therefore test butler can run on Oreo now! \o/. Just need to use the AOSP image instead of the one with Google APIs.

https://issuetracker.google.com/issues/79784000
