### ISSUE TITLE
Example custom test runner crashes 

### ISSUE THREAD

**Issue by realdadfish** [linkedin/test-butler#86]
The `README.md` states to do:

```
public class ExampleTestRunner extends AndroidJUnitRunner {
  @Override
  public void onStart() {
      TestButler.setup(ApplicationProvider.getApplicationContext());
      super.onStart();
  }

  @Override
  public void finish(int resultCode, Bundle results) {
      TestButler.teardown(ApplicationProvider.getApplicationContext());
      super.finish(resultCode, results);
  }
}
```

however, this crashed for me with androidX's test-core v1.0.0 with this: 

```
java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
   at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
   at androidx.test.core.app.ApplicationProvider.getApplicationContext(ApplicationProvider.java:41)
   at my.custom.AndroidJUnitRunner.onStart(AndroidJUnitRunner.kt:11)
   at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
```

so I figured this might be a race here that the registry doesn't know of the instrumentation yet. It is however totally unneccessary to use the registry at all, since the runner itself is the instrumentation that we need, so it is sufficient to do this:

```
public class ExampleTestRunner extends AndroidJUnitRunner {
  @Override
  public void onStart() {
      TestButler.setup(getTargetContext());
      super.onStart();
  }

  @Override
  public void finish(int resultCode, Bundle results) {
      TestButler.teardown(getTargetContext());
      super.finish(resultCode, results);
  }
}
```

This properly initialized TestButler for me, i.e. disabled animations, and ran my tests.

**Comment by drewhannay** [comment]
Thanks for reporting this. Any chance you could send a PR to update the documentation / examples?

**Comment by Kisty** [comment]
Can you try using AndroidX test `1.0.2`? I had a similar problem but it went away after updating AndroidX test.

**Comment by realdadfish** [comment]
No, `ApplicationProvider.getApplicationContext()` just redirects to the `InstrumentationRegistry`, this won't help. I'm suggesting to use the created application context of the runner itself, since `AndroidJUnitRunner` extends from `Instrumentation`.

**Comment by realdadfish** [comment]
In any case, even if it's an issue with a different `andoidx.test` version, I think it would be safer to just use the context provided by the runner itself and not one of the static accessors. But that's your call :)

**Comment by drewhannay** [comment]
I checked our code at LinkedIn and it seems like we already were using `getTargetContext()` from our `Instrumentation` subclass anyway 😅 

I agree this is probably a safer way to go anyway, so I will merge your pull request. Thanks for the contribution!

**Comment by mennatallah** [comment]
I have the same issue when I'm trying to Run my feature file as iam using a cucumber integrated with  Espresso for Android UI 
java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.	at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
